include ./theme.conf

enable_audio_bell no
background_opacity      0.95
window_margin_width     8
hide_window_decorations titlebar-only

font_family      "JetBrainsMono Nerd Font"
bold_font        "auto"
italic_font      "auto"
bold_italic_font "auto"
font_size         13

cursor_trail 1

map cmd+equal change_font_size current +0.5
