StylesPath = .
# MinAlertLevel = suggestion | warning | error
MinAlertLevel = warning

Packages = Google, alex, Joblint

# Only Markdown and .txt files; change to whatever you're using.
[*.md]
# List of styles to load.
BasedOnStyles = Vale, Google, alex, Joblint
